//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public int Id { get; set; }
        public int BookId1 { get; set; }
        public int ReaderId1 { get; set; }
        public int Direction { get; set; }
        public System.DateTime Timestamp { get; set; }
        public int Count { get; set; }
    
        public virtual Book BookId { get; set; }
        public virtual Reader ReaderId { get; set; }
    }
}
